[build]
command = "npm run build"
publish = "dist"
functions = "lambda"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/socket.io/*"
to = "/.netlify/functions/server/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200