[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/socket.io/*"
to = "/.netlify/functions/server/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200