const ACTION = {
  JOIN: "JOIN",
  JOINED: "JOINED",
  LEAVE: "LEAVE",
  DISCONNECTED: "DISCONNECTED",
  CODE_CHANGE: "CODE_CHANGE",
  CODE_RUN: "CODE_RUN",
  OUTPUT: "OUTPUT",
  SYNC_CODE: "SYNC_CODE",
};

export default ACTION;
